# Dockerfile to build test Containers

# Based on Ubuntu
FROM ubuntu
# Maintainer
COPY example.py example.py
COPY test test
# Change apt source to aliyun
RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
# Install python3 and pip3
RUN apt-get clean && apt-get update && apt-get install -y python3 python3-pip && pip install minio
# Run python3 example.py
CMD python3 example.py 